# This is a config for E2B sandbox template.
# You can use template ID (r7gjwwzi8z9x5ezdjky8) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("r7gjwwzi8z9x5ezdjky8") # Sync sandbox
# sandbox = await AsyncSandbox.create("r7gjwwzi8z9x5ezdjky8") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('r7gjwwzi8z9x5ezdjky8')

team_id = "6083f2ec-2289-4ce2-9aae-1d84331e0c85"
dockerfile = "e2b.Dockerfile"
template_id = "r7gjwwzi8z9x5ezdjky8"
