# This is a config for E2B sandbox template.
# You can use template ID (akbi9k1x2t2hlowb6q6y) or template name (ai-agent-python) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("ai-agent-python") # Sync sandbox
# sandbox = await AsyncSandbox.create("ai-agent-python") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('ai-agent-python')

team_id = "6083f2ec-2289-4ce2-9aae-1d84331e0c85"
memory_mb = 1_024
cpu_count = 2
start_cmd = "cd /home/user && python agent.py"
dockerfile = "e2b.Dockerfile"
template_name = "ai-agent-python"
template_id = "akbi9k1x2t2hlowb6q6y"
